// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "api": Application User Types
//
// Command:
// $ goagen
// --design=github.com/intervention-engine/ie/design
// --out=$(GOPATH)/src/github.com/intervention-engine/ie
// --version=v1.2.0-dirty

package client

import (
	"time"
)

// address user type.
type address struct {
	// City Name
	City *string `form:"city,omitempty" json:"city,omitempty" xml:"city,omitempty"`
	// Postal Code
	PostalCode *string `form:"postalCode,omitempty" json:"postalCode,omitempty" xml:"postalCode,omitempty"`
	// State Name
	State *string `form:"state,omitempty" json:"state,omitempty" xml:"state,omitempty"`
	// Street Name
	Street []string `form:"street,omitempty" json:"street,omitempty" xml:"street,omitempty"`
}

// Publicize creates Address from address
func (ut *address) Publicize() *Address {
	var pub Address
	if ut.City != nil {
		pub.City = ut.City
	}
	if ut.PostalCode != nil {
		pub.PostalCode = ut.PostalCode
	}
	if ut.State != nil {
		pub.State = ut.State
	}
	if ut.Street != nil {
		pub.Street = ut.Street
	}
	return &pub
}

// Address user type.
type Address struct {
	// City Name
	City *string `form:"city,omitempty" json:"city,omitempty" xml:"city,omitempty"`
	// Postal Code
	PostalCode *string `form:"postalCode,omitempty" json:"postalCode,omitempty" xml:"postalCode,omitempty"`
	// State Name
	State *string `form:"state,omitempty" json:"state,omitempty" xml:"state,omitempty"`
	// Street Name
	Street []string `form:"street,omitempty" json:"street,omitempty" xml:"street,omitempty"`
}

// riskAssessment user type.
type riskAssessment struct {
	// Date
	Date *time.Time `form:"date,omitempty" json:"date,omitempty" xml:"date,omitempty"`
	// Risk Assessment Group ID
	GroupID *string `form:"groupId,omitempty" json:"groupId,omitempty" xml:"groupId,omitempty"`
	// Risk Assessment ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Value
	Value *int `form:"value,omitempty" json:"value,omitempty" xml:"value,omitempty"`
}

// Publicize creates RiskAssessment from riskAssessment
func (ut *riskAssessment) Publicize() *RiskAssessment {
	var pub RiskAssessment
	if ut.Date != nil {
		pub.Date = ut.Date
	}
	if ut.GroupID != nil {
		pub.GroupID = ut.GroupID
	}
	if ut.ID != nil {
		pub.ID = ut.ID
	}
	if ut.Value != nil {
		pub.Value = ut.Value
	}
	return &pub
}

// RiskAssessment user type.
type RiskAssessment struct {
	// Date
	Date *time.Time `form:"date,omitempty" json:"date,omitempty" xml:"date,omitempty"`
	// Risk Assessment Group ID
	GroupID *string `form:"groupId,omitempty" json:"groupId,omitempty" xml:"groupId,omitempty"`
	// Risk Assessment ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Value
	Value *int `form:"value,omitempty" json:"value,omitempty" xml:"value,omitempty"`
}
