// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "api": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/intervention-engine/ie/design
// --out=$(GOPATH)/src/github.com/intervention-engine/ie
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// CareTeamHref returns the resource href.
func CareTeamHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/care_teams/%v", paramid)
}

// PatientHref returns the resource href.
func PatientHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/patients/%v", paramid)
}
