// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "api": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/intervention-engine/ie/design
// --out=$(GOPATH)/src/github.com/intervention-engine/ie
// --version=v1.2.0-dirty

package app

import (
	"github.com/goadesign/goa"
	"time"
)

// A care team (default view)
//
// Identifier: application/vnd.careteam+json; view=default
type CareTeam struct {
	// Timestamp for care team creation
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty" xml:"createdAt,omitempty"`
	// Unique care team ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Care team leader
	Leader *string `form:"leader,omitempty" json:"leader,omitempty" xml:"leader,omitempty"`
	// Care team name
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// A care team (link view)
//
// Identifier: application/vnd.careteam+json; view=link
type CareTeamLink struct {
	// Unique care team ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Care team name
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// CareTeamCollection is the media type for an array of CareTeam (default view)
//
// Identifier: application/vnd.careteam+json; type=collection; view=default
type CareTeamCollection []*CareTeam

// A patient (default view)
//
// Identifier: application/vnd.patient+json; view=default
type Patient struct {
	Address *Address `form:"address,omitempty" json:"address,omitempty" xml:"address,omitempty"`
	// Age of Patient
	Age *int `form:"age,omitempty" json:"age,omitempty" xml:"age,omitempty"`
	// Birth Date of Patient
	BirthDate *time.Time `form:"birthDate,omitempty" json:"birthDate,omitempty" xml:"birthDate,omitempty"`
	// Gender of Patient
	Gender *string `form:"gender,omitempty" json:"gender,omitempty" xml:"gender,omitempty"`
	// Unique patient ID
	ID              string            `form:"id" json:"id" xml:"id"`
	Name            *Name             `form:"name" json:"name" xml:"name"`
	RiskAssessments []*RiskAssessment `form:"riskAssessments,omitempty" json:"riskAssessments,omitempty" xml:"riskAssessments,omitempty"`
}

// Validate validates the Patient media type instance.
func (mt *Patient) Validate() (err error) {
	if mt.ID == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "id"))
	}
	if mt.Name == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}

// A patient (link view)
//
// Identifier: application/vnd.patient+json; view=link
type PatientLink struct {
	// Unique patient ID
	ID   string `form:"id" json:"id" xml:"id"`
	Name *Name  `form:"name" json:"name" xml:"name"`
}

// Validate validates the PatientLink media type instance.
func (mt *PatientLink) Validate() (err error) {
	if mt.ID == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "id"))
	}
	if mt.Name == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}

// PatientCollection is the media type for an array of Patient (default view)
//
// Identifier: application/vnd.patient+json; type=collection; view=default
type PatientCollection []*Patient

// Validate validates the PatientCollection media type instance.
func (mt PatientCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}
