// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "api": Application User Types
//
// Command:
// $ goagen
// --design=github.com/intervention-engine/ie/design
// --out=$(GOPATH)/src/github.com/intervention-engine/ie
// --version=v1.2.0-dirty

package app

import (
	"github.com/goadesign/goa"
	"time"
)

// careTeamPayload user type.
type careTeamPayload struct {
	// Timestamp for care team creation
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty" xml:"createdAt,omitempty"`
	// Unique care team ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Care team leader
	Leader *string `form:"leader,omitempty" json:"leader,omitempty" xml:"leader,omitempty"`
	// Care team name
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// Publicize creates CareTeamPayload from careTeamPayload
func (ut *careTeamPayload) Publicize() *CareTeamPayload {
	var pub CareTeamPayload
	if ut.CreatedAt != nil {
		pub.CreatedAt = ut.CreatedAt
	}
	if ut.ID != nil {
		pub.ID = ut.ID
	}
	if ut.Leader != nil {
		pub.Leader = ut.Leader
	}
	if ut.Name != nil {
		pub.Name = ut.Name
	}
	return &pub
}

// CareTeamPayload user type.
type CareTeamPayload struct {
	// Timestamp for care team creation
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty" xml:"createdAt,omitempty"`
	// Unique care team ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Care team leader
	Leader *string `form:"leader,omitempty" json:"leader,omitempty" xml:"leader,omitempty"`
	// Care team name
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// patientHuddle user type.
type patientHuddle struct {
	// patient id
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// reason for why patient is in this huddle
	Reason     *string    `form:"reason,omitempty" json:"reason,omitempty" xml:"reason,omitempty"`
	ReasonType *string    `form:"reason_type,omitempty" json:"reason_type,omitempty" xml:"reason_type,omitempty"`
	Reviewed   *bool      `form:"reviewed,omitempty" json:"reviewed,omitempty" xml:"reviewed,omitempty"`
	ReviewedAt *time.Time `form:"reviewed_at,omitempty" json:"reviewed_at,omitempty" xml:"reviewed_at,omitempty"`
}

// Publicize creates PatientHuddle from patientHuddle
func (ut *patientHuddle) Publicize() *PatientHuddle {
	var pub PatientHuddle
	if ut.ID != nil {
		pub.ID = ut.ID
	}
	if ut.Reason != nil {
		pub.Reason = ut.Reason
	}
	if ut.ReasonType != nil {
		pub.ReasonType = ut.ReasonType
	}
	if ut.Reviewed != nil {
		pub.Reviewed = ut.Reviewed
	}
	if ut.ReviewedAt != nil {
		pub.ReviewedAt = ut.ReviewedAt
	}
	return &pub
}

// PatientHuddle user type.
type PatientHuddle struct {
	// patient id
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// reason for why patient is in this huddle
	Reason     *string    `form:"reason,omitempty" json:"reason,omitempty" xml:"reason,omitempty"`
	ReasonType *string    `form:"reason_type,omitempty" json:"reason_type,omitempty" xml:"reason_type,omitempty"`
	Reviewed   *bool      `form:"reviewed,omitempty" json:"reviewed,omitempty" xml:"reviewed,omitempty"`
	ReviewedAt *time.Time `form:"reviewed_at,omitempty" json:"reviewed_at,omitempty" xml:"reviewed_at,omitempty"`
}

// schedulePatientPayload user type.
type schedulePatientPayload struct {
	// Date in YYYY-MM-dd format to schedule huddle
	Date *string `form:"date,omitempty" json:"date,omitempty" xml:"date,omitempty"`
	// Unique patient ID
	PatientID *string `form:"patient_id,omitempty" json:"patient_id,omitempty" xml:"patient_id,omitempty"`
}

// Validate validates the schedulePatientPayload type instance.
func (ut *schedulePatientPayload) Validate() (err error) {
	if ut.PatientID == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "patient_id"))
	}
	if ut.Date == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "date"))
	}
	return
}

// Publicize creates SchedulePatientPayload from schedulePatientPayload
func (ut *schedulePatientPayload) Publicize() *SchedulePatientPayload {
	var pub SchedulePatientPayload
	if ut.Date != nil {
		pub.Date = *ut.Date
	}
	if ut.PatientID != nil {
		pub.PatientID = *ut.PatientID
	}
	return &pub
}

// SchedulePatientPayload user type.
type SchedulePatientPayload struct {
	// Date in YYYY-MM-dd format to schedule huddle
	Date string `form:"date" json:"date" xml:"date"`
	// Unique patient ID
	PatientID string `form:"patient_id" json:"patient_id" xml:"patient_id"`
}

// Validate validates the SchedulePatientPayload type instance.
func (ut *SchedulePatientPayload) Validate() (err error) {
	if ut.PatientID == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "patient_id"))
	}
	if ut.Date == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "date"))
	}
	return
}

// address user type.
type address struct {
	// City Name
	City *string `form:"city,omitempty" json:"city,omitempty" xml:"city,omitempty"`
	// Postal Code
	PostalCode *string `form:"postalCode,omitempty" json:"postalCode,omitempty" xml:"postalCode,omitempty"`
	// State Name
	State *string `form:"state,omitempty" json:"state,omitempty" xml:"state,omitempty"`
	// Street Name
	Street []string `form:"street,omitempty" json:"street,omitempty" xml:"street,omitempty"`
}

// Publicize creates Address from address
func (ut *address) Publicize() *Address {
	var pub Address
	if ut.City != nil {
		pub.City = ut.City
	}
	if ut.PostalCode != nil {
		pub.PostalCode = ut.PostalCode
	}
	if ut.State != nil {
		pub.State = ut.State
	}
	if ut.Street != nil {
		pub.Street = ut.Street
	}
	return &pub
}

// Address user type.
type Address struct {
	// City Name
	City *string `form:"city,omitempty" json:"city,omitempty" xml:"city,omitempty"`
	// Postal Code
	PostalCode *string `form:"postalCode,omitempty" json:"postalCode,omitempty" xml:"postalCode,omitempty"`
	// State Name
	State *string `form:"state,omitempty" json:"state,omitempty" xml:"state,omitempty"`
	// Street Name
	Street []string `form:"street,omitempty" json:"street,omitempty" xml:"street,omitempty"`
}

// name user type.
type name struct {
	// Family Name
	Family *string `form:"family,omitempty" json:"family,omitempty" xml:"family,omitempty"`
	// Full Name
	Full *string `form:"full,omitempty" json:"full,omitempty" xml:"full,omitempty"`
	// Given Name
	Given *string `form:"given,omitempty" json:"given,omitempty" xml:"given,omitempty"`
	// Middle Initial
	MiddleInitial *string `form:"middleInitial,omitempty" json:"middleInitial,omitempty" xml:"middleInitial,omitempty"`
}

// Publicize creates Name from name
func (ut *name) Publicize() *Name {
	var pub Name
	if ut.Family != nil {
		pub.Family = ut.Family
	}
	if ut.Full != nil {
		pub.Full = ut.Full
	}
	if ut.Given != nil {
		pub.Given = ut.Given
	}
	if ut.MiddleInitial != nil {
		pub.MiddleInitial = ut.MiddleInitial
	}
	return &pub
}

// Name user type.
type Name struct {
	// Family Name
	Family *string `form:"family,omitempty" json:"family,omitempty" xml:"family,omitempty"`
	// Full Name
	Full *string `form:"full,omitempty" json:"full,omitempty" xml:"full,omitempty"`
	// Given Name
	Given *string `form:"given,omitempty" json:"given,omitempty" xml:"given,omitempty"`
	// Middle Initial
	MiddleInitial *string `form:"middleInitial,omitempty" json:"middleInitial,omitempty" xml:"middleInitial,omitempty"`
}

// riskAssessment user type.
type riskAssessment struct {
	// Date
	Date *time.Time `form:"date,omitempty" json:"date,omitempty" xml:"date,omitempty"`
	// Risk Assessment Group ID
	GroupID *string `form:"groupId,omitempty" json:"groupId,omitempty" xml:"groupId,omitempty"`
	// Risk Assessment ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Value
	Value *int `form:"value,omitempty" json:"value,omitempty" xml:"value,omitempty"`
}

// Publicize creates RiskAssessment from riskAssessment
func (ut *riskAssessment) Publicize() *RiskAssessment {
	var pub RiskAssessment
	if ut.Date != nil {
		pub.Date = ut.Date
	}
	if ut.GroupID != nil {
		pub.GroupID = ut.GroupID
	}
	if ut.ID != nil {
		pub.ID = ut.ID
	}
	if ut.Value != nil {
		pub.Value = ut.Value
	}
	return &pub
}

// RiskAssessment user type.
type RiskAssessment struct {
	// Date
	Date *time.Time `form:"date,omitempty" json:"date,omitempty" xml:"date,omitempty"`
	// Risk Assessment Group ID
	GroupID *string `form:"groupId,omitempty" json:"groupId,omitempty" xml:"groupId,omitempty"`
	// Risk Assessment ID
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Value
	Value *int `form:"value,omitempty" json:"value,omitempty" xml:"value,omitempty"`
}
