// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "api": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/intervention-engine/ie/design
// --out=$(GOPATH)/src/github.com/intervention-engine/ie
// --version=v1.2.0-dirty

package test
